### ISSUE TITLE
Homework Feedback - JS1 - week 1

### ISSUE THREAD

**Issue by Swapna-Sahu** [JohnYazji/hyf-homework#4]
Hi ,
Great job 🥇 . Everything looks fine for me. I can see you used "let" that's good.

I have only one comment for you.
Task - House price estimator
Task was to compare housePricePeter with 2500000 and housePriceJulia with 1000000.
Not between Peter and Julia. Please fix the logic.

Rest all looks cool to me 👍

**Comment by JohnYazji** [comment]
Hi Swapna,
Thanks for your support. Here is the updated file belw.

[index.zip](https://github.com/JohnYazji/hyf-homework/files/3820120/index.zip)
