### ISSUE TITLE
Homework Feedback JS1-Week2

### ISSUE THREAD

**Issue by ovbm** [JohnYazji/hyf-homework#5]
Hi John

Here's my feedback for your homework.

Full Name
Works great and as expected. One part of the exercise was to check if the names are not empty, you could try to adapt your code to check that a string is not empty. As a hint, there's two way to accomplish this, either with `firstname !== ""` or `firstname.length > 0`.

Winter Wear
Good job with the . my only comment would be that the last conditional could just ask if the temp is above 26 degrees, `(temperature > 26)`. That captures all temperatures above. Of course if you want to limit to realistic values, your solution makes sense.

Candy 
I think it would be best if you discussed this exercise in class. Here are some tips if you want to try again. boughtCandyPrices should start off as an empty array: `const boughtCandyPrices = []`. Next, your addCandy function should check for the name of the candy (if ..., like you did) and push the number to the array.  Another mistake you made is `boughtCandyPrices.push(weight * "chocolate")`. Here you are trying to multiply a number with a string. Try replacing the string with the actual prices from the Candy Price Table in the exercise.

I hope that helps a little, 

Best, 

Olivier

**Comment by JohnYazji** [comment]
Thanks for your comments. 💐
