### ISSUE TITLE
Homework Feedback JS1 -Week4

### ISSUE THREAD

**Issue by Swapna-Sahu** [JohnYazji/hyf-homework#7]
Great work 🥇 . Your code looks very well structured. Everything works good . But I have few things to comment : 

For add/remove task
You are saying only if the user wants to add fishing/singing  then add or else you can are not allowed to add anything. To allow user to add anything .
(lowerString.includes("fishing to")) instead write this 
lowerString.startsWith("add") && lowerString.endsWith("to my todo") same for remove
lowerString.startsWith("remove") && lowerString.endsWith("from my todo")

Enjoy coding 👍

**Comment by JohnYazji** [comment]
Thank you Swapna for your prompt reply.
